name: Fetch Node LTS Version

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-node-versions:
    runs-on: ubuntu-latest

    env:
      GIT_COMMITTER_NAME: Cron Node LTS GitHub Action
      GIT_COMMITTER_EMAIL: actions@github.com
      GIT_AUTHOR_NAME: Cron Node LTS GitHub Action
      GIT_AUTHOR_EMAIL: actions@github.com
      GITHUB_TOKEN: ${{ secrets.AUTOMERGE_PAT }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Current Package LTS Versions
        id: package_versions
        run: |
          DOCKER=$(npm run current-lts-docker --silent)
          NODEJS_ORG=$(npm run current-lts-nodejs --silent)

          echo "[package.json] LTS Version for Docker: $DOCKER"
          echo "::set-output name=DOCKER::$DOCKER"

          echo "[package.json] LTS Version for NodeJS Org: $NODEJS_ORG"
          echo "::set-output name=NODEJS_ORG::$NODEJS_ORG"

      - name: Fetch Official Node.js LTS Version
        id: official
        run: |
          VERSION=$(npm run official-lts-nodejs --silent)

          echo "Official Node.js LTS Version: $VERSION"
          echo "::set-output name=VERSION::$VERSION"

      - name: Pull Node.js LTS Docker Image
        if: steps.official.outputs.VERSION != steps.package_versions.outputs.NODEJS_ORG || steps.official.outputs.VERSION != steps.package_versions.outputs.DOCKER
        run: docker pull node:lts

      - name: Get Node.js LTS Version from Docker Image
        id: docker
        if: steps.official.outputs.VERSION != steps.package_versions.outputs.NODEJS_ORG || steps.official.outputs.VERSION != steps.package_versions.outputs.DOCKER
        run: |
          VERSION=$(docker inspect node:lts --format '{{range .Config.Env}}{{println .}}{{end}}' | grep NODE_VERSION | cut -d "=" -f2)
          echo "Node.js LTS Version from Docker: $VERSION"
          echo "::set-output name=VERSION::$VERSION"

      - name: Update package.json with New LTS Versions
        if: steps.official.outputs.VERSION != steps.package_versions.outputs.NODEJS_ORG || steps.official.outputs.VERSION != steps.package_versions.outputs.DOCKER
        run: |
          npm run update-lts -- "${{ steps.docker.outputs.VERSION }}" "${{ steps.official.outputs.VERSION }}"
          git add package.json

          # Check if there are any changes staged for commit
          if ! git diff --cached --exit-code; then
            git commit -m "Update Node.js LTS versions"
          else
            echo "No changes to commit, exiting..."
            exit 1
          fi

      - name: Bump package version
        if: steps.official.outputs.VERSION != steps.package_versions.outputs.NODEJS_ORG || steps.official.outputs.VERSION != steps.package_versions.outputs.DOCKER
        run: |
          npm version patch
          git push --follow-tags --force

